version: "3"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
     - "8881:5000"
    depends_on:
      - redis
    volumes:
      - ./api:/api
  worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./celery-queue:/queue
    entrypoint: watchmedo auto-restart -d . -p '*.py' --  celery -A  tasks worker --loglevel=info
  monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
